name: Daily submit

on:
  push:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Check file
        uses: actions/checkout@v2
      
      - name: Install env
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run
        env: 
          ID: ${{ secrets.ID }}
          PASS: ${{ secrets.PASS }}       
        run: |
          sudo cp -p ./chrome/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
          python main.py
